
name: Download and deploy
on:
  fork

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  download:
    name: Downloading the pdf and commiting it to the repo
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Fetch Github Release Asset
        uses: dsaltares/fetch-gh-release-asset@0.0.4
        with:
          repo: "rahul-sundaresan/latex-resume"
          file: "resume.pdf"
        env:
          GITHUB_TOKEN: ${{secrets.ACCESS_TOKEN}}
      - name: Print the local files
        run: ls -l
      
    



